// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAFvocrEG1L5zUCVMclQRT_rpDu6mtxIA',
    appId: '1:148241646694:web:5beb8e34880f7dcfb659a7',
    messagingSenderId: '148241646694',
    projectId: 'digitalschool-fd10d',
    authDomain: 'digitalschool-fd10d.firebaseapp.com',
    storageBucket: 'digitalschool-fd10d.appspot.com',
    measurementId: 'G-PY7XK8SD53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAXOKlz6haHGLdATVICs5H0LfQ2s5yYcw',
    appId: '1:148241646694:android:453881ec413b0da6b659a7',
    messagingSenderId: '148241646694',
    projectId: 'digitalschool-fd10d',
    storageBucket: 'digitalschool-fd10d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWPbS_qv2Mcad4z56owwrRusDthYQDp6U',
    appId: '1:148241646694:ios:14a1d0a9e8f9aa7cb659a7',
    messagingSenderId: '148241646694',
    projectId: 'digitalschool-fd10d',
    storageBucket: 'digitalschool-fd10d.appspot.com',
    iosClientId: '148241646694-j5bjlv486j3ql3kkf89jfqv61uapgjjj.apps.googleusercontent.com',
    iosBundleId: 'com.dissingardjino.digitaldschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWPbS_qv2Mcad4z56owwrRusDthYQDp6U',
    appId: '1:148241646694:ios:14a1d0a9e8f9aa7cb659a7',
    messagingSenderId: '148241646694',
    projectId: 'digitalschool-fd10d',
    storageBucket: 'digitalschool-fd10d.appspot.com',
    iosClientId: '148241646694-j5bjlv486j3ql3kkf89jfqv61uapgjjj.apps.googleusercontent.com',
    iosBundleId: 'com.dissingardjino.digitaldschool',
  );
}
